// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Note struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Type      string `json:"type"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Query struct {
}

type Review struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Year      int     `json:"year"`
	Month     *int    `json:"month,omitempty"`
	Week      *int    `json:"week,omitempty"`
	Notes     []*Note `json:"notes"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}
